spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/puce_market
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  user-contact:
    stub:
      phone-by-username: {}
